const triggerError = (req, res, next) => {
  // Esta es una excepci√≥n intencional
  throw new Error("Intentional server error triggered!")
}

module.exports = { triggerError }